#################################################################################
# Copyright (c) 2020 ArSysOp
#
# This program and the accompanying materials are made available under the
# terms of the MIT which is available at
# https://spdx.org/licenses/MIT.html#licenseText
#
# SPDX-License-Identifier: MIT
#
# Contributors:
#     ArSysOp - initial API and implementation
#################################################################################

name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build jTR
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/test-coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true